version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    command: redis-server --save 60 1 --dir /data
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "./db/:/data"
    restart: unless-stopped