version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    environment:
      - REDIS_ARGS="--save 60 1"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "./db/:/data"
    restart: unless-stopped
  database-api:
    platform: linux/amd64
    depends_on:
      - redis-stack
    build: pages
    ports:
      - "23214:8000"
    secrets:
      - dotenv

secrets:
  dotenv:
    file: .env